language:
    - cpp

before_install:
    - wget http://www.cmake.org/files/v2.8/cmake-2.8.10.tar.gz
    - tar xf *.tar.gz
    - cd cmake-*
    - ./configure
    - make

install:
    - sudo make install

before_script:
    - which cmake
    - cmake --version
    - cd ..

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
