language:
    - objective-c

install:
    - brew install cmake

script:
    - cmake --version
    - mkdir -p _builds/xcode
    - mkdir -p _builds/make
    - cd _builds/xcode
    - cmake -GXcode ../..
    - cd ../..
    - cd _builds/make
    - cmake ../..
